apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-rielu
  namespace: web-rielu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-rielu
  template:
    metadata:
      labels:
        app: web-rielu
    spec:
      initContainers:
        - name: init-html
          image: nginx:latest
          command: ['sh', '-c', 'cp -r /usr/share/nginx/html/* /data/']
          volumeMounts:
            - name: storage
              mountPath: /data
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: storage
              mountPath: /usr/share/nginx/html # マウント先
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: web-content-pvc
