apiVersion: v1
kind: ConfigMap
metadata:
  name: site-a-html
data:
  index.html: |
    <!doctype html>
    <html lang="ja">
      <head>
        <meta charset="utf-8" />
        <title>site-a</title>
      </head>
      <body>
        <h1>site-a from nginx</h1>
        <p>Argo CD がこのサイトをデプロイしています。</p>
      </body>
    </html>
