apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rielulinks-ingress
  namespace: web-rielulinks
annotations:
  kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: public
  rules:
    - host: rielulinks.uniproject.jp
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
