apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: web-rielulinks
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv6
  selector:
    app: web-rielulinks
  ports:
    - port: 80
      targetPort: 80
