apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: site-b
spec:
  ingressClassName: public
  rules:
    - host: site-b.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
