apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: websites
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: REPLACE_WITH_YOUR_REPO_URL
        revision: HEAD
        directories:
          - path: k8s/sites/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: websites
      source:
        repoURL: REPLACE_WITH_YOUR_REPO_URL
        targetRevision: HEAD
        path: '{{path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true