apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: websites
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/penti-nameko/k8s-homepages.git
        revision: main
        directories:
          - path: k8s/sites/*
  template:
    metadata:
      name: 'web-{{path.basename}}'
    spec:
      project: websites
      source:
        repoURL: https://github.com/penti-nameko/k8s-homepages.git
        targetRevision: main
        path: '{{path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'web-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true